default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: practice_angular_with_rails_development

test:
  <<: *default
  database: practice_angular_with_rails_test